# Generated by Django 5.1.4 on 2024-12-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Nazwa użytkownika')),
                ('first_name', models.CharField(max_length=30, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nazwisko')),
                ('role', models.CharField(choices=[('dispatcher', 'Dyspozytor'), ('medic', 'Ratownik medyczny')], default='dispatcher', max_length=20, verbose_name='Rola')),
            ],
        ),
    ]
